# Generated by Django 4.2.7 on 2023-11-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField()),
                ('nome_aluno', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=100)),
                ('observacao', models.TextField()),
                ('data_matricula', models.DateTimeField(auto_now_add=True, verbose_name='Data de matrícula')),
            ],
            options={
                'verbose_name': 'Matrícula de Aluno',
                'verbose_name_plural': 'Matrículas de Alunos',
                'ordering': ['nome_aluno'],
            },
        ),
    ]
